import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const main = async () => {
  const seeds = [
    { keyword: 'トマト', normalizedKeyword: 'とまと' },
    { keyword: 'お弁当のおかず', normalizedKeyword: 'おべんとうのおかず' },
  ];

  for (const seed of seeds) {
    const existing = await prisma.talkKeyword.findFirst({
      where: {
        userId: null,
        normalizedKeyword: seed.normalizedKeyword,
      },
    });

    if (!existing) {
      await prisma.talkKeyword.create({
        data: {
          ...seed,
          isAutoGenerated: true,
          userId: null,
        },
      });
      console.log(`Created: ${seed.keyword}`);
    } else {
      console.log(`Skipped (already exists): ${seed.keyword}`);
    }
  }
};

main()
  .then(async () => await prisma.$disconnect())
  .catch(async (e) => {
    console.error('[Seed Script] Failed', e);
    await prisma.$disconnect();
    process.exit(1);
  });
