import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const main = async () => {
  const keywordsData = [
    { keyword: 'トマト', normalizedKeyword: 'トマト' },
    { keyword: 'お弁当のおかず', normalizedKeyword: 'お弁当のおかず' },
  ];

  for (const keywordData of keywordsData) {
    const existing = await prisma.talkKeyword.findFirst({
      where: {
        userId: null,
        normalizedKeyword: keywordData.normalizedKeyword,
      },
    });

    if (!existing) {
      await prisma.talkKeyword.create({
        data: {
          ...keywordData,
          isAutoGenerated: true,
          userId: null,
        },
      });
      console.log(`Created: ${keywordData.keyword}`);
    } else {
      console.log(`Skipped (already exists): ${keywordData.keyword}`);
    }
  }
};

main()
  .then(async () => await prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
