import { requireUserId } from '@/lib/apiServer/requireUserId';
import type {
  SuggestCollection,
  SuggestItem,
  SuggestLabel,
} from '@/lib/schema/suggestItemSchema';
import { suggestLabelSchema } from '@/lib/schema/suggestItemSchema';
import { prisma } from '@/lib/utils/prisma';
import { NextRequest, NextResponse } from 'next/server';
import { ZodError } from 'zod';

export async function GET(request: NextRequest) {
  try {
    const userId = await requireUserId(request);
    if (!userId) {
      return NextResponse.json({ error: 'UNAUTHORIZED' }, { status: 401 });
    }

    const select = {
      keyword: true,
      normalizedKeyword: true,
    };

    const [seedKeywords, popularKeywords, recentKeywords] = await Promise.all([
      prisma.talkKeyword.findMany({
        where: {
          isAutoGenerated: true,
          isVisible: true,
        },
        orderBy: { createdAt: 'desc' },
        select,
        take: 2,
      }),

      prisma.talkKeyword.findMany({
        where: {
          userId,
          isVisible: true,
        },
        orderBy: [{ usageCount: 'desc' }, { lastUsedAt: 'desc' }],
        select,
        take: 3,
      }),

      prisma.talkKeyword.findMany({
        where: {
          userId,
          isVisible: true,
        },
        orderBy: { lastUsedAt: 'desc' },
        select,
        take: 3,
      }),
    ]);

    const priority: Record<SuggestLabel, number> = {
      seed: 3,
      popular: 2,
      recent: 1,
    };

    const pasteLabel = [
      { array: seedKeywords, label: suggestLabelSchema.parse('seed') },
      { array: popularKeywords, label: suggestLabelSchema.parse('popular') },
      { array: recentKeywords, label: suggestLabelSchema.parse('recent') },
    ];

    const pasteLabelItems: SuggestItem[] = pasteLabel.flatMap(
      ({ array, label }) => array.map((item) => ({ ...item, label }))
    );

    const selectWord = new Map<string, SuggestItem>();
    for (const item of pasteLabelItems) {
      const exist = selectWord.get(item.normalizedKeyword);

      if (!exist) {
        selectWord.set(item.normalizedKeyword, item);
        continue;
      }

      if (priority[item.label] > priority[exist.label]) {
        selectWord.set(item.normalizedKeyword, item);
      }
    }

    const selectArray = Array.from(selectWord.values());

    const classLabel = selectArray.reduce<SuggestCollection>(
      (acc, item) => {
        acc[item.label].push(item);
        return acc;
      },
      { seed: [], popular: [], recent: [] }
    );

    const { seed, popular, recent } = classLabel;

    return NextResponse.json({
      seed,
      popular,
      recent,
    });
  } catch (e) {
    console.error('[Suggest API] GET validation failed', e);

    if (e instanceof ZodError) {
      return NextResponse.json({ error: 'INVALID_REQUEST' }, { status: 400 });
    }
    console.error('[Suggest API] GET unexpected error', e);

    return NextResponse.json(
      { error: 'INTERNAL_SERVER_ERROR' },
      { status: 500 }
    );
  }
}
