import { createErrorResponse } from '@/lib/apiServer/createErrorResponse';
import { requireUserId } from '@/lib/apiServer/requireUserId';
import {
  type SuggestCollection,
  suggestCollectionSchema,
  type SuggestItem,
  type SuggestType,
  suggestTypeSchema,
} from '@/lib/schema/suggestSchema';
import { prisma } from '@/lib/utils/prisma';
import { NextRequest, NextResponse } from 'next/server';
import { ZodError } from 'zod';

export async function GET(request: NextRequest) {
  try {
    const userId = await requireUserId(request);
    if (!userId) {
      return createErrorResponse('UNAUTHORIZED', 401);
    }

    const select = {
      keyword: true,
      normalizedKeyword: true,
    };

    const [seedKeywords, popularKeywords, recentKeywords] = await Promise.all([
      prisma.talkKeyword.findMany({
        where: {
          isAutoGenerated: true,
          isVisible: true,
        },
        orderBy: { createdAt: 'desc' },
        select,
        take: 2,
      }),

      prisma.talkKeyword.findMany({
        where: {
          userId,
          isVisible: true,
        },
        orderBy: [{ usageCount: 'desc' }, { lastUsedAt: 'desc' }],
        select,
        take: 3,
      }),

      prisma.talkKeyword.findMany({
        where: {
          userId,
          isVisible: true,
        },
        orderBy: { lastUsedAt: 'desc' },
        select,
        take: 3,
      }),
    ]);

    const priority: Record<SuggestType, number> = {
      seed: 3,
      popular: 2,
      recent: 1,
    };

    const pasteLabel = [
      { array: seedKeywords, label: suggestTypeSchema.parse('seed') },
      { array: popularKeywords, label: suggestTypeSchema.parse('popular') },
      { array: recentKeywords, label: suggestTypeSchema.parse('recent') },
    ];

    const pasteLabelItems: SuggestItem[] = pasteLabel.flatMap(
      ({ array, label }) => array.map((item) => ({ ...item, label }))
    );

    const selectWord = new Map<string, SuggestItem>();
    for (const item of pasteLabelItems) {
      const exist = selectWord.get(item.normalizedKeyword);

      if (!exist) {
        selectWord.set(item.normalizedKeyword, item);
        continue;
      }

      if (priority[item.label] > priority[exist.label]) {
        selectWord.set(item.normalizedKeyword, item);
      }
    }

    const selectArray = Array.from(selectWord.values());

    const classLabel = selectArray.reduce<SuggestCollection>(
      (acc, item) => {
        acc[item.label].push(item);
        return acc;
      },
      { seed: [], popular: [], recent: [] }
    );

    const parsed = suggestCollectionSchema.parse(classLabel);
    const { seed, popular, recent } = parsed;

    return NextResponse.json({
      seed,
      popular,
      recent,
    });
  } catch (e) {
    if (e instanceof ZodError) {
      console.error('[Suggest API] GET Validation failed', e);
      return createErrorResponse('INVALID_FORMAT', 400);
    }
    console.error('[Suggest API] GET Unexpected error', e);
    return createErrorResponse('INTERNAL_SERVER_ERROR', 500);
  }
}
