import type { AiKeywords } from '@/lib/schema/recipeBlockSchema';
import { prisma } from '@/lib/utils/prisma';

export async function upsertTalkKeywords(
  userId: number,
  keywords: AiKeywords
): Promise<void> {
  const now = new Date();

  await Promise.all(
    keywords.map((word) => {
      return prisma.talkKeyword.upsert({
        where: {
          userId_normalizedKeyword: {
            userId,
            normalizedKeyword: word.normalizedKeyword,
          },
        },
        update: {
          usageCount: { increment: 1 },
          lastUsedAt: now,
        },
        create: {
          userId,
          keyword: word.keyword,
          normalizedKeyword: word.normalizedKeyword,
          usageCount: 1,
          lastUsedAt: now,
          isAutoGenerated: false,
        },
      });
    })
  );
}

export async function saveRecipeTags(
  recipeId: number,
  keywords: AiKeywords
): Promise<void> {
  await Promise.all(
    keywords.map(async (word) => {
      const recipeTag = await prisma.recipeTag.upsert({
        where: { tag: word.keyword },
        update: {},
        create: {
          tag: word.keyword,
        },
      });

      return prisma.recipeTagRelation.upsert({
        where: {
          recipeId_tagId: {
            recipeId,
            tagId: recipeTag.id,
          },
        },
        update: {},
        create: {
          recipeId,
          tagId: recipeTag.id,
        },
      });
    })
  );
}
