import type { AiKeywords } from '@/lib/schema/recipeBlockSchema';
import { prisma } from '@/lib/utils/prisma';

export async function upsertTalkKeywords(
  userId: number,
  keywords: AiKeywords
): Promise<void> {
  const now = new Date();

  try {
    await Promise.all(
      keywords.map((word) => {
        return prisma.talkKeyword.upsert({
          where: {
            userId_normalizedKeyword: {
              userId,
              normalizedKeyword: word.normalizedKeyword,
            },
          },
          update: {
            usageCount: { increment: 1 },
            lastUsedAt: now,
          },
          create: {
            userId,
            keyword: word.keyword,
            normalizedKeyword: word.normalizedKeyword,
            usageCount: 1,
            lastUsedAt: now,
            isAutoGenerated: false,
          },
        });
      })
    );
  } catch (e) {
    console.error('[Talk API] POST Critical keywords update failure', {
      error: e instanceof Error ? e.stack : e,
      userId,
      keywords,
    });
  }
}

export async function saveRecipeTags(
  recipeId: number,
  keywords: AiKeywords
): Promise<void> {
  try {
    await Promise.all(
      keywords.map(async (word) => {
        const recipeTag = await prisma.recipeTag.upsert({
          where: { tag: word.keyword },
          update: {},
          create: {
            tag: word.keyword,
          },
        });

        return prisma.recipeTagRelation.upsert({
          where: {
            recipeId_tagId: {
              recipeId,
              tagId: recipeTag.id,
            },
          },
          update: {},
          create: {
            recipeId,
            tagId: recipeTag.id,
          },
        });
      })
    );
  } catch (e) {
    console.error('[RecipeTag] Failed to save recipe tags', {
      recipeId,
      error: e,
    });
  }
}
