import { prisma } from '@/lib/utils/prisma';

export async function updateTalkKeyword(
  userId: number,
  keywords: string[],
  normalizedKeywords: string[]
): Promise<void> {
  if (!keywords.length) {
    console.warn('[Talk API] No keywords provided for update', { userId });
    return;
  }

  const talkKeyword = keywords
    .map((keyword, index) => {
      const cleanKeyword = keyword?.normalize('NFKC').trim() ?? '';
      const cleanNormalized =
        normalizedKeywords[index]?.normalize('NFKC').trim() ?? '';
      return { keyword: cleanKeyword, normalizedKeyword: cleanNormalized };
    })
    .filter((word) => {
      word.keyword && word.normalizedKeyword;
    });

  const now = new Date();

  try {
    await Promise.all(
      talkKeyword.map((word) => {
        return prisma.talkKeyword.upsert({
          where: {
            userId_normalizedKeyword: {
              userId,
              normalizedKeyword: word.normalizedKeyword,
            },
          },
          update: {
            usageCount: { increment: 1 },
            lastUsedAt: now,
          },
          create: {
            userId,
            keyword: word.keyword,
            normalizedKeyword: word.normalizedKeyword,
            usageCount: 1,
            lastUsedAt: now,
            isAutoGenerated: false,
          },
        });
      })
    );
  } catch (e) {
    console.error('[Talk API] Critical keywords update failure', {
      error: e instanceof Error ? e.stack : e,
      userId,
      keywords,
    });
  }
}
