import { prisma } from '@/lib/utils/prisma';

export async function updateTalkKeyword(
  userId: number,
  keywords: { keyword: string; normalizedKeyword: string }[]
): Promise<void> {
  if (!keywords.length) {
    console.warn('[Talk API] POST No keywords provided for update', {
      userId,
    });
    return;
  }

  const keywordPairs = keywords
    .map((word) => ({
      keyword: word.keyword?.normalize('NFKC').trim() ?? '',
      normalizedKeyword: word.normalizedKeyword?.normalize('NFKC').trim() ?? '',
    }))
    .filter((word) => word.keyword && word.normalizedKeyword);

  if (!keywordPairs.length)
    console.warn('[Talk API] POST KeywordPairs empty', {
      keywords,
    });

  const now = new Date();

  try {
    await Promise.all(
      keywordPairs.map((word) => {
        return prisma.talkKeyword.upsert({
          where: {
            userId_normalizedKeyword: {
              userId,
              normalizedKeyword: word.normalizedKeyword,
            },
          },
          update: {
            usageCount: { increment: 1 },
            lastUsedAt: now,
          },
          create: {
            userId,
            keyword: word.keyword,
            normalizedKeyword: word.normalizedKeyword,
            usageCount: 1,
            lastUsedAt: now,
            isAutoGenerated: false,
          },
        });
      })
    );
  } catch (e) {
    console.error('[Talk API] POST Critical keywords update failure', {
      error: e instanceof Error ? e.stack : e,
      userId,
      keywords,
    });
  }
}
